# Copyright 2026 Christopher Wright
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Resource paths for the packaged HALucinator configs.

Everything the device needs to run ships inside the installed package and is
resolved from the *installed* location via ``importlib.resources``, so the
device runs from anywhere -- no cwd assumptions and no PYTHONPATH hack.

THE FIRMWARE IS NOT SHIPPED. QMK is GPLv2 and this repository is
AGPL-3.0-or-later; no firmware bytes and no QMK source are committed.
``tools/extract_firmware.py`` regenerates ``configs/planck.bin`` (and the
generated ``planck_addrs.yaml`` / ``planck_facts.yaml``) from the vendor
artifact.
"""
from __future__ import annotations

import importlib.resources as _ir
from pathlib import Path

PACKAGE = "rehostry_planck"

#: The config files handed to `halucinator.main -c ...`, in load order.
#: `planck_addrs.yaml` is GENERATED by tools/extract_firmware.py -- its
#: `intercepts:` are appended to this config's (hal_config.py appends rather
#: than overriding), so the seams move with a firmware rebuild.
CONFIG_FILES = [
    "planck_config.yaml",
    "planck_addrs.yaml",
]

FIRMWARE_BIN = "planck.bin"


def configs_dir() -> Path:
    """Absolute path to the packaged configs/ dir (also where firmware lives)."""
    return Path(str(_ir.files(PACKAGE))) / "configs"


def config_paths() -> list:
    return [configs_dir() / f for f in CONFIG_FILES]


def firmware_bin() -> Path:
    return configs_dir() / FIRMWARE_BIN


def firmware_present() -> bool:
    return firmware_bin().is_file()
